# Generated by Django 5.0.3 on 2024-04-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_address_line_3_additionaladdress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_line_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line_5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
