# Generated by Django 5.0.2 on 2024-04-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('500-1000', '500 to 1000'), ('1000-2000', '1000 to 2000'), ('2000-3000', '2000 to 3000'), ('3000-4000', '3000 to 4000'), ('4000-5000', '4000 to 5000')], max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
