# Generated by Django 5.0.2 on 2024-04-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_filterprice_delete_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterPrice',
        ),
    ]
